/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#4700a7",
        "tertiary-container": "#7000ff",
        "tertiary-dim": "#874cff",
        "error-container": "#9f0519",
        "on-secondary-fixed": "#354500",
        "on-background": "#f6f6fc",
        "on-error": "#490006",
        "surface": "#0c0e12",
        "surface-container-low": "#111318",
        "error-dim": "#d7383b",
        "surface-container-high": "#1d2025",
        "secondary-dim": "#b7e500",
        "outline-variant": "#46484d",
        "on-secondary": "#455900",
        "on-primary-fixed": "#003f43",
        "on-tertiary-fixed": "#1f0052",
        "secondary-fixed-dim": "#b7e500",
        "secondary-fixed": "#c3f400",
        "inverse-on-surface": "#53555a",
        "tertiary": "#ac89ff",
        "on-surface": "#f6f6fc",
        "surface-container": "#171a1f",
        "primary-dim": "#00deec",
        "on-primary": "#005d63",
        "tertiary-fixed-dim": "#b190ff",
        "primary": "#8ff5ff",
        "surface-container-highest": "#23262c",
        "surface-bright": "#292c33",
        "on-error-container": "#ffa8a3",
        "surface-variant": "#23262c",
        "outline": "#74757a",
        "surface-dim": "#0c0e12",
        "on-surface-variant": "#aaabb0",
        "secondary-container": "#506600",
        "surface-tint": "#8ff5ff",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-fixed": "#bda1ff",
        "error": "#ff716c",
        "secondary": "#c3f400",
        "on-secondary-container": "#efffbc",
        "primary-container": "#00eefc",
        "on-tertiary-container": "#f8f1ff",
        "primary-fixed-dim": "#00deec",
        "on-tertiary": "#290067",
        "inverse-primary": "#006a71",
        "surface-container-lowest": "#000000",
        "on-primary-container": "#005359",
        "on-secondary-fixed-variant": "#4e6300",
        "background": "#0c0e12",
        "primary-fixed": "#00eefc",
        "inverse-surface": "#f9f9ff"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [],
}
